# Generated by Django 4.2.5 on 2023-10-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginationt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={},
        ),
    ]
