# Generated by Django 4.2.5 on 2023-10-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginationt_app', '0002_alter_apikey_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apikey',
            new_name='insert_data',
        ),
        migrations.AlterModelTable(
            name='insert_data',
            table=None,
        ),
    ]
