# Generated by Django 4.2.5 on 2023-10-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginationt_app', '0005_abcd_delete_insert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='abcd',
            new_name='apikey',
        ),
    ]
